# Generated by Django 5.0.4 on 2024-07-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalExpense', models.IntegerField(default=0)),
                ('TotalEarning', models.IntegerField(default=0)),
                ('SavingPerMonth', models.IntegerField(default=0)),
                ('TotalInvestment', models.IntegerField(default=0)),
                ('TotalLiabilities', models.IntegerField(default=0)),
                ('NetWorth', models.IntegerField(default=0)),
                ('EmergencyFund', models.IntegerField(default=0)),
                ('RetirementFund', models.IntegerField(default=0)),
                ('HouseFund', models.IntegerField(default=0)),
                ('ExpectedSavings_6months', models.IntegerField(default=0)),
                ('Retirement_monthly_gap', models.IntegerField(default=0)),
                ('Savings_gap', models.IntegerField(default=0)),
                ('Home_downpayment_gap', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EarningItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Salary', models.IntegerField(default=0)),
                ('Bonus', models.IntegerField(default=0)),
                ('Interest', models.IntegerField(default=0)),
                ('PartTime', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rent', models.IntegerField(default=0)),
                ('Maintenance', models.IntegerField(default=0)),
                ('Electricity', models.IntegerField(default=0)),
                ('netflix', models.IntegerField(default=0)),
                ('youtube', models.IntegerField(default=0)),
                ('amazon_prime', models.IntegerField(default=0)),
                ('onedrive', models.IntegerField(default=0)),
                ('Grocery', models.IntegerField(default=0)),
                ('Misc', models.IntegerField(default=5000)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock', models.IntegerField(default=0)),
                ('MutualFund', models.IntegerField(default=0)),
                ('Gold', models.IntegerField(default=0)),
                ('RealEstate', models.IntegerField(default=0)),
                ('Crypto', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LiabilitiesItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonalLoan', models.IntegerField(default=0)),
                ('CreditCard', models.IntegerField(default=0)),
                ('MotherLoan', models.IntegerField(default=0)),
                ('MedicalInsurance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NPS', models.IntegerField(default=0)),
                ('PF', models.IntegerField(default=0)),
                ('LiquidFund', models.IntegerField(default=0)),
                ('FixedDeposit', models.IntegerField(default=0)),
                ('HouseDownPayment', models.IntegerField(default=0)),
            ],
        ),
    ]
