# Generated by Django 5.0.4 on 2024-07-02 05:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saVex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitems',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
