# Generated by Django 5.0.4 on 2024-07-02 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saVex', '0002_expenseitems_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregateditems',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 7, 2, 15, 2, 37, 943050)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='earningitems',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 7, 2, 15, 3, 15, 152144)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentitems',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 7, 2, 15, 3, 18, 782853)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liabilitiesitems',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 7, 2, 15, 3, 22, 797404)),
            preserve_default=False,
        ),
    ]
