# Generated by Django 5.0.4 on 2024-07-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saVex', '0003_aggregateditems_date_earningitems_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liabilitiesitems',
            name='CreditLoan',
            field=models.IntegerField(default=0),
        ),
    ]
