# Generated by Django 5.0.4 on 2024-07-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saVex', '0006_alter_expenseitems_misc'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregateditems',
            name='month',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='earningitems',
            name='month',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='expenseitems',
            name='month',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='investmentitems',
            name='month',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='liabilitiesitems',
            name='month',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='savingsitems',
            name='month',
            field=models.IntegerField(default=7),
        ),
    ]
