# Generated by Django 5.0.4 on 2024-10-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saVex', '0007_aggregateditems_month_earningitems_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregateditems',
            name='month',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='earningitems',
            name='month',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='expenseitems',
            name='month',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='investmentitems',
            name='month',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='liabilitiesitems',
            name='month',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='savingsitems',
            name='month',
            field=models.IntegerField(default=10),
        ),
    ]
